version: '3.1' 
services:
  db: 
    image: mysql:5.7 
    restart: always 
    volumes: 
      - db:/var/lib/mysql
  wordpress: 
    image: wordpress 
    restart: always
    # this user setting is needed for my perlscript to run in the jenkins tests
    user: root:root
    ports: 
      - 8081:80 
    volumes: 
      - wordpress:/var/www/html 
volumes: 
  wordpress: 
  db:
